/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Checkboard: typeof import('./../components/ui/patterns/Checkboard.vue')['default']
    FrameOutline: typeof import('./../components/ui/primitives/FrameOutline.vue')['default']
    LayerBackdrop: typeof import('./../components/ui/layer/Backdrop.vue')['default']
    LayerContent: typeof import('./../components/ui/layer/Content.vue')['default']
    PageFooter: typeof import('./../components/page/Footer.vue')['default']
    PageHeader: typeof import('./../components/page/Header.vue')['default']
    PageMain: typeof import('./../components/page/Main.vue')['default']
    Quads: typeof import('./../components/ui/patterns/Quads.vue')['default']
    QuadsGrid: typeof import('./../components/ui/patterns/QuadsGrid.vue')['default']
    Strip: typeof import('./../components/ui/primitives/Strip.vue')['default']
    Stripes: typeof import('./../components/ui/patterns/Stripes.vue')['default']
    TabGameList: typeof import('./../components/tab/GameList.vue')['default']
    TabInventory: typeof import('./../components/tab/Inventory.vue')['default']
    TabProfile: typeof import('./../components/tab/profile/Profile.vue')['default']
    TabProfileBackdrop: typeof import('./../components/tab/profile/Backdrop.vue')['default']
    TabWatchList: typeof import('./../components/tab/WatchList.vue')['default']
  }
}

// For TSX support
declare global {
  const Checkboard: typeof import('./../components/ui/patterns/Checkboard.vue')['default']
  const FrameOutline: typeof import('./../components/ui/primitives/FrameOutline.vue')['default']
  const LayerBackdrop: typeof import('./../components/ui/layer/Backdrop.vue')['default']
  const LayerContent: typeof import('./../components/ui/layer/Content.vue')['default']
  const PageFooter: typeof import('./../components/page/Footer.vue')['default']
  const PageHeader: typeof import('./../components/page/Header.vue')['default']
  const PageMain: typeof import('./../components/page/Main.vue')['default']
  const Quads: typeof import('./../components/ui/patterns/Quads.vue')['default']
  const QuadsGrid: typeof import('./../components/ui/patterns/QuadsGrid.vue')['default']
  const Strip: typeof import('./../components/ui/primitives/Strip.vue')['default']
  const Stripes: typeof import('./../components/ui/patterns/Stripes.vue')['default']
  const TabGameList: typeof import('./../components/tab/GameList.vue')['default']
  const TabInventory: typeof import('./../components/tab/Inventory.vue')['default']
  const TabProfile: typeof import('./../components/tab/profile/Profile.vue')['default']
  const TabProfileBackdrop: typeof import('./../components/tab/profile/Backdrop.vue')['default']
  const TabWatchList: typeof import('./../components/tab/WatchList.vue')['default']
}