/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackdropLayer: typeof import('./components/layers/BackdropLayer.vue')['default']
    Checkboard: typeof import('./components/patterns/Checkboard.vue')['default']
    ContentLayer: typeof import('./components/layers/ContentLayer.vue')['default']
    FrameOutline: typeof import('./components/patterns/primitives/FrameOutline.vue')['default']
    GameList: typeof import('./components/sections/GameList.vue')['default']
    IconCustomProfile: typeof import('./src/assets/images/icons/profile.svg?component')['default']
    IconProfile: typeof import('@/assets/images/icons/profile.svg?component')['default']
    Inventory: typeof import('./components/sections/Inventory.vue')['default']
    PageFooter: typeof import('./components/page/Footer.vue')['default']
    PageHeader: typeof import('./components/page/Header.vue')['default']
    PageMain: typeof import('./components/page/Main.vue')['default']
    Profile: typeof import('./components/sections/profile/Profile.vue')['default']
    ProfileBackdrop: typeof import('./components/sections/profile/Backdrop.vue')['default']
    Quads: typeof import('./components/patterns/Quads.vue')['default']
    QuadsGrid: typeof import('./components/patterns/QuadsGrid.vue')['default']
    Strip: typeof import('./components/patterns/primitives/Strip.vue')['default']
    Stripes: typeof import('./components/patterns/Stripes.vue')['default']
    WatchList: typeof import('./components/sections/WatchList.vue')['default']
  }
}

// For TSX support
declare global {
  const BackdropLayer: typeof import('./components/layers/BackdropLayer.vue')['default']
  const Checkboard: typeof import('./components/patterns/Checkboard.vue')['default']
  const ContentLayer: typeof import('./components/layers/ContentLayer.vue')['default']
  const FrameOutline: typeof import('./components/patterns/primitives/FrameOutline.vue')['default']
  const GameList: typeof import('./components/sections/GameList.vue')['default']
  const IconCustomProfile: typeof import('./src/assets/images/icons/profile.svg?component')['default']
  const IconProfile: typeof import('@/assets/images/icons/profile.svg?component')['default']
  const Inventory: typeof import('./components/sections/Inventory.vue')['default']
  const PageFooter: typeof import('./components/page/Footer.vue')['default']
  const PageHeader: typeof import('./components/page/Header.vue')['default']
  const PageMain: typeof import('./components/page/Main.vue')['default']
  const Profile: typeof import('./components/sections/profile/Profile.vue')['default']
  const ProfileBackdrop: typeof import('./components/sections/profile/Backdrop.vue')['default']
  const Quads: typeof import('./components/patterns/Quads.vue')['default']
  const QuadsGrid: typeof import('./components/patterns/QuadsGrid.vue')['default']
  const Strip: typeof import('./components/patterns/primitives/Strip.vue')['default']
  const Stripes: typeof import('./components/patterns/Stripes.vue')['default']
  const WatchList: typeof import('./components/sections/WatchList.vue')['default']
}