/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-svg-components

import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconProfile: typeof import('@/assets/images/icons/profile.svg?component')['default']
    LogoGithub: typeof import('@/assets/images/socials/github.svg?component')['default']
    LogoKoFi: typeof import('@/assets/images/socials/ko-fi.svg?component')['default']
    LogoPronounsPage: typeof import('@/assets/images/socials/pronouns-page.svg?component')['default']
    LogoSpotify: typeof import('@/assets/images/socials/spotify.svg?component')['default']
    LogoTelegram: typeof import('@/assets/images/socials/telegram.svg?component')['default']
    LogoTwitter: typeof import('@/assets/images/socials/twitter.svg?component')['default']
  }
}

// For TSX support
declare global {
  const IconProfile: typeof import('@/assets/images/icons/profile.svg?component')['default']
  const LogoGithub: typeof import('@/assets/images/socials/github.svg?component')['default']
  const LogoKoFi: typeof import('@/assets/images/socials/ko-fi.svg?component')['default']
  const LogoPronounsPage: typeof import('@/assets/images/socials/pronouns-page.svg?component')['default']
  const LogoSpotify: typeof import('@/assets/images/socials/spotify.svg?component')['default']
  const LogoTelegram: typeof import('@/assets/images/socials/telegram.svg?component')['default']
  const LogoTwitter: typeof import('@/assets/images/socials/twitter.svg?component')['default']
}
